### ISSUE TITLE
Fr Rust bro?

### ISSUE THREAD

**Issue by pingponghero12** [wojteq18/Cryptography#1]
Bro why rust bro? You for real with this shit?

**Comment by pingponghero12** [comment]
```rust
mod RSA;
mod encryption;
mod unencryption;
fn main() 
{
    let (p, q, n, fi_n) = RSA::generate_rsa_values();
    println!("p: {}, q: {}, n: {}, fi_n: {}", p, q, n, fi_n);
    let (e) = RSA::generate_e(fi_n);
    println!("Wprowadź wiadomość, którą chcesz zaszyfrować: ");
    let mut massage = String::new();
    std::io::stdin().read_line(&mut massage).expect("Błąd wczytyania danych");
    let massage = massage.trim();
    let ascii = encryption::to_ascii(massage);
    let encryption = encryption::encrypt(massage, e, n);
    println!("Wiadomość w postaci ASCII: {:?}", ascii);
    println!("Zaszyfrowana wiadomość: {:?}", encryption);
    let mut d: u128 = unencryption::find_d(e, fi_n);
    let decryption = unencryption::decrypt(encryption, n, e, d);
    println!("Odszyfrowana wiadomość: {:?}", decryption);
}
```
Bro bro.

Still you got this bro bro, I belive in you! :muscle: :+1:

**Comment by wojteq18** [comment]
Bro, it may look like shit, but at least it's not 2000 lines in one file bro. it's just a testDnia 23 listopada 2024 20:49:48 CET, Manfred Gawlas ***@***.***> napisał(a):

mod RSA;
mod encryption;
mod unencryption;
fn main() 
{
    let (p, q, n, fi_n) = RSA::generate_rsa_values();
    println!("p: {}, q: {}, n: {}, fi_n: {}", p, q, n, fi_n);
    let (e) = RSA::generate_e(fi_n);
    println!("Wprowadź wiadomość, którą chcesz zaszyfrować: ");
    let mut massage = String::new();
    std::io::stdin().read_line(&mut massage).expect("Błąd wczytyania danych");
    let massage = massage.trim();
    let ascii = encryption::to_ascii(massage);
    let encryption = encryption::encrypt(massage, e, n);
    println!("Wiadomość w postaci ASCII: {:?}", ascii);
    println!("Zaszyfrowana wiadomość: {:?}", encryption);
    let mut d: u128 = unencryption::find_d(e, fi_n);
    let decryption = unencryption::decrypt(encryption, n, e, d);
    println!("Odszyfrowana wiadomość: {:?}", decryption);
}
Bro bro.
Still you got this bro bro, I belive in you! 💪 👍

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID:
***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/wojteq18/Cryptography/issues/1#issuecomment-2495635229",
"url": "https://github.com/wojteq18/Cryptography/issues/1#issuecomment-2495635229",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
--
Wysłane z aplikacji OnetPoczta
------N33XZ5RHQKFMAZKDLEAPSYHO6JEGG9
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: 8bit

Bro, it may look like shit, but at least it's not 2000 lines in one file bro. it's just a test

Dnia 23 listopada 2024 20:49:48 CET, Manfred Gawlas  napisał(a):
>```rust
>mod RSA;
>mod encryption;
>mod unencryption;
>fn main() 
>{
>    let (p, q, n, fi_n) = RSA::generate_rsa_values();
>    println!("p: {}, q: {}, n: {}, fi_n: {}", p, q, n, fi_n);
>    let (e) = RSA::generate_e(fi_n);
>    println!("Wprowadź wiadomość, którą chcesz zaszyfrować: ");
>    let mut massage = String::new();
>std::io::stdin().read_line(&mut massage).expect("Błąd wczytyania
>danych");
>    let massage = massage.trim();
>    let ascii = encryption::to_ascii(massage);
>    let encryption = encryption::encrypt(massage, e, n);
>    println!("Wiadomość w postaci ASCII: {:?}", ascii);
>    println!("Zaszyfrowana wiadomość: {:?}", encryption);
>    let mut d: u128 = unencryption::find_d(e, fi_n);
>    let decryption = unencryption::decrypt(encryption, n, e, d);
>    println!("Odszyfrowana wiadomość: {:?}", decryption);
>}
>```
>Bro bro.
>
>Still you got this bro bro, I belive in you! :muscle: :+1: 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wojteq18/Cryptography/issues/1#issuecomment-2495635229
>You are receiving this because you are subscribed to this thread.
>
>Message ID: 

--
Wysłane z aplikacji OnetPoczta
------N33XZ5RHQKFMAZKDLEAPSYHO6JEGG9--

**Comment by wojteq18** [comment]
Rust to zbazowany język broDnia 23 listopada 2024 20:47:41 CET, Manfred Gawlas ***@***.***> napisał(a):

Bro why rust bro? You for real with this shit?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/wojteq18/Cryptography/issues/1",
"url": "https://github.com/wojteq18/Cryptography/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
--
Wysłane z aplikacji OnetPoczta
------B5ZS6ON5C4ZA800PFOUE37AF12HVZG
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: 8bit

Rust to zbazowany język bro

Dnia 23 listopada 2024 20:47:41 CET, Manfred Gawlas  napisał(a):
>Bro why rust bro? You for real with this shit?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wojteq18/Cryptography/issues/1
>You are receiving this because you are subscribed to this thread.
>
>Message ID: 

--
Wysłane z aplikacji OnetPoczta
------B5ZS6ON5C4ZA800PFOUE37AF12HVZG--

**Comment by wojteq18** [comment]
Bro, it may look like shit, but at least it's not 2000 lines in one file bro. it's just a test

**Comment by pingponghero12** [comment]
You got me here bro.
